# Header
menu:
  首页: /lingdong/
  关于: /lingdong/about
  存档: /lingdong/archives
rss: /lingdong/atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- logo
- info
- category
- tagcloud
- recent_posts
- blogroll


# Miscellaneous
google_analytics:
favicon: lingdong/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

baidu_tongji: false